"$schema" = "https://starship.rs/config-schema.json"

add_newline = true
format = """
[](surface0)\
$os\
[](bg:peach fg:surface0)\
$directory\
[ ](fg:peach)\
$line_break\
$character"""
palette = "catppuccin_mocha"
scan_timeout = 10

[palettes.catppuccin_mocha]
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
peach = "#fab387"
purple = "#cba6f7"
red = "#f38ba8"
surface0 = "#313244"
text = "#cdd6f4"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
EndeavourOS = ""
Fedora = "󰣛"
Gentoo = "󰣨"
Linux = "󰌽"
Macos = "󰀵"
Manjaro = ""
Mint = "󰣭"
Raspbian = "󰐿"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = "󰍲"

[directory]
format = "[ $path ]($style)"
style = "fg:mantle bg:peach"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Developer = "󰲋 "
Documents = "󰈙 "
Downloads = " "
Music = "󰝚 "
Pictures = " "

[line_break]
disabled = false

[character]
disabled = false
error_symbol = "[](bold fg:red)"
success_symbol = "[](bold fg:green)"
vimcmd_replace_one_symbol = "[](bold fg:purple)"
vimcmd_replace_symbol = "[](bold fg:purple)"
vimcmd_symbol = "[](bold fg:green)"
vimcmd_visual_symbol = "[](bold fg:lavender)"
