# Reload this config with <prefix> r.
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded tmux config"

# Use Ctrl-Space as the prefix.
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on
set -g status-position top
set -g default-terminal "tmux-256color"

# Vim-style pane navigation.
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Plugins.
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "catppuccin/tmux#v2.3.0"

# Catppuccin.
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

set -g status-right-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"

run "~/.tmux/plugins/tpm/tpm"
